[package]
name = "rusty_bus"
version = "0.1.0"
edition = "2021"
authors = ["Paolo <pvictorsys@gmail.com>"]
readme = "README.md"
repository = "https://github.com/paoloposso/rusty_bus"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amiquip = { version = "0.4", default-features = false }
futures = "0.3"
tokio = {version="1.6.1", features = ["full"]}