[package]
name = "crosstown_bus"
version = "0.1.1"
edition = "2021"
authors = ["paoloposso <pvictorsys@gmail.com>"]
readme = "README.md"
repository = "https://github.com/paoloposso/crosstown_bus"
description = "Event Bus with RabbitMQ for Rust"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amiquip = { version = "0.4", default-features = false }
futures = "0.3"